name: security_checker

description: "A new Flutter project."

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.6.0-266.0.dev

dependencies:
  flutter:
    sdk: flutter

  qr_code_scanner:
    path: ./plugins/qr_code_scanner
  ar_flutter_plugin_flutterflow:
    path: ./plugins/ar_flutter_plugin_flutterflow
  flutter_overlay_window: ^0.4.5
  provider: ^6.1.2
  vector_math: ^2.1.1
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1

  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  firebase_core: ^3.10.0

  http: ^1.3.0
  dio: ^5.7.0
  responsive_framework: ^1.5.1
  google_ml_kit: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/safe_object.glb
    - assets/unsafe_object.glb
